/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#003257",
        "inverse-surface": "#e5e2e1",
        "on-primary": "#522300",
        "surface-variant": "#353534",
        "surface-container-high": "#2a2a2a",
        "tertiary-fixed-dim": "#9dcaff",
        "on-secondary-fixed": "#1a1c1c",
        "on-primary-fixed-variant": "#743500",
        "surface-container-lowest": "#0e0e0e",
        "on-error": "#690005",
        "error-container": "#93000a",
        "tertiary-fixed": "#d1e4ff",
        "surface-container-highest": "#353534",
        "inverse-on-surface": "#313030",
        "surface-dim": "#131313",
        "secondary-container": "#454747",
        "surface-tint": "#ffb68a",
        primary: "#ffb68a",
        "secondary-fixed-dim": "#c6c6c6",
        "on-error-container": "#ffdad6",
        tertiary: "#9dcaff",
        "on-background": "#e5e2e1",
        "inverse-primary": "#984700",
        "surface-container-low": "#1c1b1b",
        "on-primary-container": "#4b2000",
        "on-tertiary-fixed-variant": "#00497c",
        background: "#131313",
        "on-secondary-fixed-variant": "#454747",
        "primary-container": "#e8720c",
        "on-secondary": "#2f3131",
        "outline-variant": "#574236",
        "primary-fixed": "#ffdbc8",
        "on-tertiary-container": "#002e51",
        "on-surface": "#e5e2e1",
        "on-surface-variant": "#dec1b0",
        surface: "#131313",
        "primary-fixed-dim": "#ffb68a",
        "tertiary-container": "#0098f9",
        outline: "#a68b7d",
        "on-secondary-container": "#b4b5b5",
        secondary: "#c6c6c6",
        "surface-container": "#201f1f",
        "on-tertiary-fixed": "#001d35",
        "on-primary-fixed": "#321300",
        error: "#ffb4ab",
        "surface-bright": "#3a3939",
        "secondary-fixed": "#e2e2e2",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "16px",
        unit: "4px",
        "container-max": "1280px",
        margin: "24px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "code-md": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-lg": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "code-md": ["14px", { lineHeight: "1.6", fontWeight: "400" }],
      },
      keyframes: {
        "glow-pulse": {
          "0%, 100%": {
            filter:
              "drop-shadow(0 0 24px rgba(232,114,12,0.35)) drop-shadow(0 0 80px rgba(232,114,12,0.15))",
          },
          "50%": {
            filter:
              "drop-shadow(0 0 48px rgba(232,114,12,0.55)) drop-shadow(0 0 140px rgba(232,114,12,0.25))",
          },
        },
        "cursor-blink": {
          "0%, 49%": { opacity: "1" },
          "50%, 100%": { opacity: "0" },
        },
        "fade-in-up": {
          "0%": { transform: "translateY(20px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
      },
      animation: {
        "glow-pulse": "glow-pulse 5s ease-in-out infinite",
        "cursor-blink": "cursor-blink 1.1s linear infinite",
        "fade-in-up": "fade-in-up 800ms cubic-bezier(0.16, 1, 0.3, 1) both",
      },
    },
  },
  plugins: [],
};
